# Generated by Django 4.2 on 2023-04-08 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBarnd',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=uuid.uuid4, serialize=False)),
                ('brand_name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='products')),
            ],
            options={
                'verbose_name_plural': 'Computer Brands',
            },
        ),
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=150)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='computer.computerbarnd')),
            ],
            options={
                'verbose_name_plural': 'Computer Specifications',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_code', models.CharField(editable=False, max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_rate', models.IntegerField()),
                ('total_price', models.IntegerField(editable=False)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='computer.computerspecification')),
            ],
        ),
    ]
